### ISSUE TITLE
Assign multiple materials to one 3D model

### ISSUE THREAD

**Issue by ZhaiQW** [TomographicImaging/gVXR-Tutorials#1]
Hi Dr Vidal,

I am using the gVXR for my X-ray CT simulation, and my sample consists of different components made from different materials. I've created a .stl 3D model of my sample, however, I am not sure how can I assign different materials to different parts of the 3D model via gVXR, may I ask for your help? Thank you very much!

![Image](https://github.com/user-attachments/assets/4fe9841c-6e7b-47ab-9457-11bcc0dfc938)

**Comment by effepivi** [comment]
Hi ZhaiQW,

sorry for my late reply, I missed your message.
You need at least one STL file per material.

There is an example in [multi_material-lungman_phantom.ipynb](https://github.com/TomographicImaging/gVXR-Tutorials/blob/main/notebooks/multi_material-lungman_phantom.ipynb). Section 5 on *Set the Sample* shows how to use several meshes from STL files. Each mesh must be identified with a label (string). You can use the label to set the material property corresponding to each STL file. In your case you'll use `setCompound` and `setDensity` instead of `setHounsfieldUnit`.

Please let me know if you need further assistance.

regards,

Franck

**Comment by ZhaiQW** [comment]
Hi Dr Vidal,

Received your solution, thank you very much for your help!
